#pragma once

//作为r0和r3公用的一个文件，通常是用来作为控制代码的公用文件，当然这里也是

#define PROCESS_PROTECT_NAME L"ProcessProtect"

//IO控制码，具体这样定义的原因就不详述了
#define IOCTL_PROCESS_PROTECT_BY_PID	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROCESS_UNPROTECT_BY_PID	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROCESS_PROTECT_CLEAR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
